config/routes.rb
Treebook::Application.routes.draw do
  get "profiles/show"

  devise_for :views

  devise_for :users
  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
    get 'edit', to: 'devise/registrations#edit', as: :edit
  end
  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  get "/:id", to: "profiles#show"

end

app/models/status.rb
class Status < ActiveRecord::Base
	#user_id is not native
  attr_accessible :content, :user_id 
  	#user is native to ruby and can recognize user_id
  	#Allows us retrieve a user for a given status (status.user). Then we can use ser methods on this user obj to return the name of the user!
  	#A Status belongs_to only one user. Allows us to retrieve a status that belongs to a single user.
  belongs_to :user
  # Makes sure that a user enters content into our status object.
  validates :content, presence: true,
                      length: { minimum: 2}
  # Makes sure a user_id is present on a status.
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model (IN DATABASE)
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :profile_name
  # attr_accessible :title, :body

  #The opposite of belongs_to. This says that a User has many statuses. This links multiple statuses to a user.
  has_many :statuses

  #Rails validation that makes sure that the users first_name is ENTERED when a User object is created/saved!
  #Other VALIDATIONS online in rails documentation.
  # /\A[a-zA-Z\-\_]+\Z/,
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :profile_name, presence: true,
                           uniqueness: true,
                           format: {
                            #Makes sure profile names contain every char except white space
                            with: /^[a-zA-Z0-9_-]+$/,
                            #If has white space, this failure messsage is specified.
                            message: "Must be formatted correctly."
                            }

  def full_name
  	first_name + " " + last_name
  end
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	# Conditional will allow for both tests to pass. If a user is found, profile page is viewed. Else 404 is viewed.
  	@user = User.find_by_profile_name(params[:id])
  	if @user
  		# Can use in the views and controller! Instance variable
  		@statuses = @user.statuses.all
  		render action: :show
  	else 
  		render file: "public/404", status: 404, formats: [:html]
  	end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  # Before filters will run before anything else in the controller. :authenticate_user! devise helper?
  # Add this to authenticate a user before they can make a post.
  # only: on the new method defined below. For new statuses, users must be logged in!
  # Controller manages the interaction with the server and manages views. 
  # This before filter will authenticate a user before new, create, edit, and update features are accessed.
  # Note: Rails automatically redirects these users to the login page.
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update] 
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = Status.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Helper function that adds the class to notice/alert flash messages for proper alert colors.
	def flash_class (type)
		case type
		when :alert
			 "alert-warning"
		when :notice
			 "alert-success"
		else
			 "alert-warning"
		end
	end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treebook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-default navbar-fixed-top" role="navigation">
		<div class="navbar-inner">
			<div class="container">
				<a href="#" class="navbar-brand">Treebook</a>
				<ul class="nav navbar-nav navbar-left">
					<!-- This is included here becuase this link is in the header which is always present! -->
      				<li><%= link_to "All Statuses", feed_path %></li> 
      			</ul>
      			<ul class="nav navbar-nav navbar-right">
      				<% if user_signed_in? %>
      					<!-- Note, you can replace new_user_registration_path with register_path since we gave it an as: :register. Same with other paths! -->
	      				<li><%= link_to current_user.full_name, edit_path %></li>
	      				<!-- Note: we had to delete the ", method: :delete %>" argument when chagning from the original path -->
	      				<li><%= link_to "Log Out", logout_path %></li>
      				<% else %>
      					<li><%= link_to "Register", register_path %></li>
      					<li><%= link_to "Login ", login_path %></li>
      				<% end %>
      			</ul>
			</div>
		</div>
	</div>
	<div class="container">
		<!-- Checks for an alert. Note: "" or 0 === false -->
		<% flash.each do |type, message| %>
			<div class="alert alert-dismissable <%= flash_class type %>">
  				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  				<!-- erb here displays the flash notice messages -->
  				<%= message %>
			</div>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/profiles/show.html.erb
<div class="page-header">
	<h1><%= @user.full_name %></h1>
</div>
<!-- If statuses are present for this user, display them -->
<% if @statuses %>
	<% @statuses.each do |status| %>
		<div class="well">
			<%= status.content %>
			<hr />
			<%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
		</div>
	<% end %>
<% end %>

app/views/statuses/_form.html.erb
<%= simple_form_for (@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :user_id, collection: User.all, label_method: :full_name %>
  <%= f.input :content %>
  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header">
	<h1>All of the statuses</h1>
</div>

<%= link_to "Post", new_status_path, class: "btn btn-default" %>

<!-- erb LOOPS -->
<% @statuses.each do |status| %>
	<!-- Note: This is the post selected in the statuses.css.scss. Other status styling goes here normally -->
	<div class="status">
		<strong><%= status.user.full_name %></strong>
		<p><%= status.content %></p>
		<div class="meta">
			<%= link_to time_ago_in_words(status.created_at) + " ago", status %>
			<span class="admin">
				|<%= link_to "Edit", edit_status_path(status) %> |
				<%= link_to "Delete", status, method: :delete, data: { confirm: "Are you sure you sure?"} %>
			</span>
		</div>
	</div>
<% end %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @status.user.full_name %>
</p>

<p>
  <b>Content:</b>
  <%= @status.content %>
</p>


<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>